/*
* This file is only present so that xgettext can extract strings that are not present in the code (mostly planet names)
* We try to cover the planets/moons included in the base installation of Orbiter
*/

_c("Proper name", "Sun")
_c("Proper name", "Sol")
_c("Proper name", "Mercury")
_c("Proper name", "Venus")
_c("Proper name", "Earth")
_c("Proper name", "Moon")
_c("Proper name", "Mars")
_c("Proper name", "Phobos")
_c("Proper name", "Deimos")
_c("Proper name", "Vesta")
_c("Proper name", "Jupiter")
_c("Proper name", "Saturn")
_c("Proper name", "Uranus")
_c("Proper name", "Neptune")
_c("Proper name", "Ariel")
_c("Proper name", "Miranda")
_c("Proper name", "Nereid")
_c("Proper name", "Oberon")
_c("Proper name", "Proteus")
_c("Proper name", "Titania")
_c("Proper name", "Triton")
_c("Proper name", "Umbriel")
_c("Proper name", "Callisto")
_c("Proper name", "Europa")
_c("Proper name", "Ganymede")
_c("Proper name", "Io")
_c("Proper name", "Dione")
_c("Proper name", "Enceladus")
_c("Proper name", "Hyperion")
_c("Proper name", "Iapetus")
_c("Proper name", "Mimas")
_c("Proper name", "Rhea")
_c("Proper name", "Tethys")
_c("Proper name", "Titan")
